import { Plugin } from 'vite'
import { minify, Options as HTMLMinifierOptions } from 'html-minifier-terser'

export interface Options {
  minifierOptions?: HTMLMinifierOptions
}

export default function minifyHTML({ minifierOptions }: Options = {}): Plugin {
  return {
    name: 'minify-html-plugin',
    transformIndexHtml: (html) => {
      const minified = minify(html, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        includeAutoGeneratedTags: false,
        removeAttributeQuotes: true,
        removeOptionalTags: true,
        removeScriptTypeAttributes: true,
        useShortDoctype: true,
        ...minifierOptions,
      })
      return minified
    },
  }
}
